apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-test
  namespace: gitlab-runner
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: gitlab-runner
  name: gitlab-test
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-test
  namespace: gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-test
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-test
  apiGroup: rbac.authorization.k8s.io
